apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  values:
    controller:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      image:
        tag: "v1.2.0"
