apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  releaseName: nginx-controller
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: "4.0.17"
  interval: 0h10m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      config:
        use-forwarded-headers: true
      replicaCount: 1
      service:
        external:
          enabled: true
